name: "claim_resolve"
version: "1.0.0"
config-version: 2

profile: "claim_resolve"

model-paths: ["models"]
seed-paths: ["seeds"]
clean-targets: ["target", "dbt_packages"]

models:
  claim_resolve:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
